// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package manageincoming

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeAssetTrackerManageincoming(in *jlexer.Lexer, out *MarketInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "market":
			out.Market = int(in.Int())
		case "price":
			out.Price = float64(in.Float64())
		case "volume":
			out.Volume = float64(in.Float64())
		case "is_buy":
			out.IsBuy = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeAssetTrackerManageincoming(out *jwriter.Writer, in MarketInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"market\":"
		out.RawString(prefix)
		out.Int(int(in.Market))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"volume\":"
		out.RawString(prefix)
		out.Float64(float64(in.Volume))
	}
	{
		const prefix string = ",\"is_buy\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBuy))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MarketInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeAssetTrackerManageincoming(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MarketInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeAssetTrackerManageincoming(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MarketInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeAssetTrackerManageincoming(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MarketInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeAssetTrackerManageincoming(l, v)
}
